services:
  apache-seata-server:
    image: apache/seata-server:2.2.0
    restart: always
    environment:
      TZ: Asia/Shanghai
  mysql-for-a-service:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: Asia/Shanghai
    volumes:
      - mysql-data-a:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
  mysql-for-b-service:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: Asia/Shanghai
    volumes:
      - mysql-data-b:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
  a-service:
    image: linghengqian/a-service:latest
    pull_policy: build
    build:
      context: ./a-service
      dockerfile_inline: |
        FROM ghcr.io/graalvm/native-image-community:22.0.2 AS nativebuild
        WORKDIR /build
        COPY ./ .
        RUN ./mvnw -DskipTests=true clean native:compile -PnativeCustom
        
        FROM gcr.io/distroless/java-base-debian12:latest
        COPY --from=nativebuild /build/target/*.so /
        COPY --from=nativebuild /build/target/app /
        ENTRYPOINT [ "/app" ]
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      apache-seata-server:
        condition: service_started
      mysql-for-a-service:
        condition: service_healthy
    environment:
      TZ: Asia/Shanghai
  b-service:
    image: linghengqian/b-service:latest
    pull_policy: build
    build:
      context: ./b-service
      dockerfile_inline: |
        FROM ghcr.io/graalvm/native-image-community:22.0.2 AS nativebuild
        WORKDIR /build
        COPY ./ .
        RUN ./mvnw -DskipTests=true clean native:compile -PnativeCustom
        
        FROM gcr.io/distroless/java-base-debian12:latest
        COPY --from=nativebuild /build/target/*.so /
        COPY --from=nativebuild /build/target/app /
        ENTRYPOINT [ "/app" ]
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      apache-seata-server:
        condition: service_started
      mysql-for-b-service:
        condition: service_healthy
      a-service:
        condition: service_started
    environment:
      TZ: Asia/Shanghai
volumes:
  mysql-data-a:
  mysql-data-b:
